namespace: shared-testing
controllerType: Deployment
app: { id: "003", name: "diwa-app", env: "testing" }
image: { repository: "my-reg/diwa-app", tag: "6-b866df1" }
service: { port: 80, targetPort: 3000 }
secretData:
  PORT: "3000"
  DB_HOST: "svc-diwa-app-db-003"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "admin123"
  DB_NAME: "diwa_db"
