namespace: testing
controllerType: Deployment
app:
    id: "004"
    name: todo-app
    env: testing
image:
    repository: docker.io/devopsnaratel/todo-app-php
    tag: build-3-bea2047-dev
service:
    port: 80
    targetPort: 3000
secretData:
    DB_HOST: ENC[AES256_GCM,data:6UkTewlLmEbgKDsEsrf9uNqZ9g==,iv:o/kVk/GDqwmIxgdWTGvGAm5vO6Y7Gm4+jAR/ytdkXG8=,tag:zt8jvvlzfTMO9U3WlgNavg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:AianFwD1SB3c3I/Ne40=,iv:GAzbP5wu+UMANV7qhGqF2dD5YtpRD4ajnZaB3NEeqBM=,tag:G05OK7x6fHftHHqbN2pjlQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:d82TyWzkQWyTccY=,iv:kg+jYTWV/eVrrfkcpDQ5k1icP00oWx+xG+URIOQR5TA=,tag:xQYvpw4Go+nO6xEQU+4qDA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:ZpGIgg==,iv:kLryhG3xYdqXW4Ocyk2GPn+lXlPnje3W24fnPO/xzQk=,tag:Zrng28l1KcnR6CHcO19S5A==,type:str]
    DB_USER: ENC[AES256_GCM,data:DnnFN8oOIqk=,iv:m3jnxWaFMoHznWsMLKY6pkdDCcoMgnC8VtxIEXhy4Dg=,tag:u4JtLjUtWzKNvFBL6Y+EEw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:WJiJlXJTE2dggMk=,iv:nHoxUzU/sXWSA8fK02Sm9kpixDMZPQubDqokYa9asbM=,tag:qS9F3sZ6K/+EEgZ56+d4cg==,type:str]
    PORT: ENC[AES256_GCM,data:CvWMTg==,iv:ATvTOJK7WekjFeot+kC0SZuiJv7KCXBVknYV10rRByk=,tag:PAIlphI1KcUuwQclUwwOyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ3B1eWdmdlNzUzVsMmlD
            ZXFtQWZjaGVEZUZuUzJRbU1XcUY1YlhyY0RRCk9TZVlOamNWbHhOMStHdllwU3Bk
            WmxVdUVkSlNReVpyV3ErUnAzL3hYVW8KLS0tIGphMzRXb2NhQmsxRnBPZlVxZjNj
            TGRsdVRZRldVQ2V6Y0ttOU9ES1B5YlEKXJQ6Z5b60BrapBIXIv+CGoLnLpapwtCc
            kBFSb/puqHDd+DJEY3dXPL3wKz2jd4jQ75huTounzqpazLQX1Esx9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T03:58:49Z"
    mac: ENC[AES256_GCM,data:qLlWGHjUMtSChVb8LLTiPeWvquDEj5rJ1cPkfjC87At+HpKSuRcJk8JlnOG53j5/y1VVXIlbQB2rxV6AW03/KbCdEvNUFUceSvoamSLCjfZDH4YLOt9f/4Rds52grpTlfxmSqaOfGUoQFc02ehS4u1EzGVDHak+AyFvy88uMYls=,iv:CKzPZPfmB1UszWpTOpoVF71R+Q7M8rAJrc1Ck3+MvQ8=,tag:6khT7hSHAFL4TcfWAOojYA==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
