namespace: prod
controllerType: StatefulSet
app:
    id: "001"
    name: todoapp-db
    env: prod
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:Fe3N5eVgDDflwzh+00E=,iv:JEabOpDNwwAGkqjfQF+jlL5B/dZG1i4BSlCoy3yJm5Q=,tag:BPJahGDA4qoifOdjatOwqQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:5lJWrYqBOmR04Dr8lC+uLA==,iv:VEQp9a1oCdH+nCsqNDy7CpTHWeZ9wAYDTzGSngMQg9w=,tag:WgrmortL2oOMjWu989I2zw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qCWX9GHxKd9wAQY=,iv:AOuBNguc+mXaosYzar16LI4ocpF5f+rPzX1lMn8jPj4=,tag:8W5x1xOMbpZgrD1qQuEZQA==,type:str]
backup:
    enabled: true
    type: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRStUbzAyQnNHcXdRNDk4
            WWhSeHVIK0FyRU5ydU1wbHIzWkdEcWRHekQ0Ck9tTjEzZ3hCNlpobnNNTHhwL3pk
            OXV4ME5VUGJxZ0lxanJrYzJtcHFjUVUKLS0tIFU2MTlGeERpdFlIZUpuWW5FUmZM
            ZWRKbHdsdXp0cHlrZXBVQXNXZ2ZQQlkKNYvu/JEOZ6ywlsbLK9+6I61QLGQW0Z5o
            cL8Yh+tX6EJ+WFrcZmVBuUus1g45MdmOjnlv+4XfRpkVNBMi1CpB2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T03:30:59Z"
    mac: ENC[AES256_GCM,data:8AHhzigWJKUq56z2Qpxnu06Edm4O/VKYQSjHUBvz0KmVhKDV61rqaK421PGIggWMSrtCgIQtPdZq1ehU9SMQ7ga+riMjU+wCjWy+62uoCRMq0sn0CnXQGz3ZriHo2LuHjiQldC4Io541c0rBeyIuSUx9BKu3y+DV7NKrrzsmkso=,iv:h8VzA10XSErxaItAPFFKPLCAuaVeqW4TumXd3IOBZ3A=,tag:k98rsZHq0RIfz0dkRtNEhQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
