namespace: prod
controllerType: StatefulSet
app:
    id: "001"
    name: todoapp
    env: prod
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:tNrPVD8ObxHyoSeBMsM=,iv:mso2XsMMs35UciVDGKsMDuNG6WSxyuZuaEI6qUJUFRE=,tag:5y4s+DGMlC/DwRR+yUG3og==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:NcpPVwf9ZPPDZwWKrdK9ng==,iv:2qNKROkijsXMIYogYFjAo9dDAp0DfBUbO7UF1skYBaE=,tag:yankNWXaurcsMXrkbM0Ptw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:C16BOYTCnsFzTSM=,iv:BLMP+Q1/bvhJEj8A7WI7DZj6rZqsf+P1LdWeI0PprOE=,tag:ldYOeYvaJEQXG6vociC1pg==,type:str]
backup:
    enabled: true
    type: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaW1BOW9ZaEhPNTVQUFMw
            RFp4ZERNYkJJb0FKaFJndFVvY3pQN0lzelVFCkd2TVJtcFRBT2VKOEt3V1Zhdzdp
            YW4zQUV1UGZSd0oza0tLQnl5TGJvZjgKLS0tIG4rR1FBLzR0Q253L3pra2MyN2Fa
            SEYwVFVtU0dTMHNmM00wbFNRcytOazAKI0+iY8GNljv72gsj39aT6l5VRt7sbOq/
            hzQ70TlVPMO2rqdGL593XRvcaG5O2W+4BBORZOqYql5VDnwJ4BQQfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T02:19:16Z"
    mac: ENC[AES256_GCM,data:7zOtlIjynym0C0OLjWfnU/KXW8MEwFSS8BoBoPRiQKcyb8T83tt0V6Gk5ivw9HIxPxaYi8h/Wb/wkKGVfvbaM3dcVPJyLI0qfaIr4IVHi9Ig189i0VWoUuRGb7zMcP3+MxRg1Z+tzN/9eIasi/L/FNhzQUkmjI9h7xVqju+zn5o=,iv:2oMlXz7efdLRPakgDS2nM4hhkXLx03Sh5luYqgEnNj0=,tag:CxaLO64ytP9FbGVQ3kCTgA==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
