namespace: prod
controllerType: StatefulSet
app:
    id: "001"
    name: todoapp-db
    env: prod
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:3ZYj4bIpDwuwxwK3NaQ=,iv:Xfp0KMSFq+6HdOyr7Gx5JpYx4kyrdIMgklhRitNEkvM=,tag:Cekhq/F1uJHI7cz4AdTDnw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:sgq45lYx/5aRctvs7E3jZw==,iv:6+tl5YisD2xYKL8SrQ16V31idHdyBGVf8rJRhOE6JWQ=,tag:5yFF84HD2giSq69FQYq2iw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/pAHXSMy9dx+4Ng=,iv:/X5AW9YaU3pTcBt3KI/LImvAJ4ijQ9KSOcnH/r12B/4=,tag:18y564ZlYwImDCXTrIPlWw==,type:str]
backup:
    enabled: true
    type: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFhqZWd6bVp2U1dHZE1T
            enZXU0lLTWx3Vjg0RDJNUittZklaR0ZubWdRCjJ3OHZ1eEszWGFmbEpyUUpDVDN1
            dFhnclpwTUZ3SG1HUE8yZ3M1czdSQ00KLS0tIFFTbGxuUTRySlI3dnV4MnkxVmgy
            bld6OW5FQldSdEJMb1Zndk1oTlFDZkUKFuG8S0DoP/nGRWgZMiF2cqI80A8+uIcb
            QXiNSzRXTKBbfjOP5YUy9Y8R4ThNgpWhw6b4wK5U3aXuYJ0kabuQ5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T03:39:45Z"
    mac: ENC[AES256_GCM,data:e9cBxVlYIChIXPrVb2SSEf+33bD+zPryikmsy9kBnjsYic+j2HqIZ6k7JZIJqrIbpoTonetxdurT3f0K5KXXGTyDUMvMW5KSmLS7bYSHkqFRLxD8dYjQ0Wh1pF/wB5aRdEeM7kMI8Ecm1/4rkuhjuh9TK/mAnt8FApFYANQO4+Y=,iv:GMNWPF30qadFSkzFKjpydggkUQ9JeiVeoxkyJY/qOzw=,tag:dBWFGp1VLebjka5pr4wKkQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
