namespace: testing
controllerType: StatefulSet
app:
    id: "001"
    name: todoapp
    env: testing
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:dY7CJnThVGOIYrVXyWA=,iv:ZRvPY0+n0Q1UdIteUGisd/3riDoWgwY8QFLb908llRw=,tag:qGIh0uhJVYLgosiCq/5ZaA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:2FGgtzPNRlETL0jtKUGDdA==,iv:FitgncsEFMaRuiIU3ewB102LpkMxpgOlndLa4wUOwew=,tag:4yDL7hz/EPJwT0SJkufkMA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XBpcIR40xDEaZJs=,iv:znaDUxosfEjg0nd+6MmlaY4ogh/3nqbC7oboW92QoOI=,tag:8V1qsUADMKYBB0jMrK/KHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN2s2TUpaQWNVMEZxWWJp
            UHFuOTVLVTMxWHRqcFJtZ0lGQUJnbGlOTEY0CmZqZjBranlzTHR5dE5sUDBjWmU4
            WkhVOWtKdGdGRWZ1eXU3N1VYK3dyTzQKLS0tIHFSd2pYSWRrbHRuTWk3RXhEL21L
            OWoyN0xyaWRyZXJZSUtTRE9HaisyeHMKMln4+lht8xiF51nPTAnnMoize+9aqXdM
            o/Tk/4wH/t2eKXPgWF8RIHZYBxrYI1A7kn+74SFF1/6EEJlurJcD1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T02:19:16Z"
    mac: ENC[AES256_GCM,data:q9Nr/rdbYpzbAuhQy7ixofH+3gzHy/4N94N1/zJDIYNAFLZEzWTX3wxw4eMpLo8UKOXvAqZwv6qRndXBCeEB01LT2fItxpTN0BRqk9xQsGqUYR6wulVCVRRwtTI0yxCbEESDMngk1OOnWuMt3Mgh3CFV26TUt0ItAlX+k8KxL0g=,iv:RjJnebZTJIWhDvpWNvR2UHOPnoS5SWgrvpWxEmmamrQ=,tag:1vPOH+wyNEVSPsiLX6DOXw==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
