namespace: testing
controllerType: StatefulSet
app:
    id: "001"
    name: todoapp-db
    env: testing
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYnNXdnFmYWE4V1d5dGZu
            L1JWVmd2WWFNYXR2MjRoWWhtam00aEhqa0gwCnZQcjJ1eGIxcDNnZmt4bEVpNWc5
            b1lkemsvdVdTSTZRNGgwSEUxTnRKTkUKLS0tIHhnSVFLSkFPeE54Q2hZb2RENG4y
            Um9ObmtlVFhoRERnVTZvRU1RZTlMRXcK/SVwlrp+ZdBcLQW0G722i5dWJN2jxPAm
            fOAJmoF3e6PMsU7P8vrQAeSpnI7nbkD8gddQYtG9f7IYQnNEGXYQuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:48:36Z"
    mac: ENC[AES256_GCM,data:EHT89ZZof4yetohqUnlzxdyiUE46ramtIPzEL+bpLPPy7VMMhs/hNhkHNUFtaFodwA+dSpCGl4dxpKE5vNekt3b1IX3TG0sNy10TEy9ydT+uDPVj6YjlPtzH1UhoK/cUpk9Hy4aLvg3wBTxI7No+3RksTnQLU8s9n/SzbZ3ftb8=,iv:Gy3w92jvKIzCARmXtcsCrE+DZ7IKbCcJBl+RHzYRN6s=,tag:jV3nIRL4j/kE4b3ul+6vGw==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
