namespace: prod
controllerType: StatefulSet
app:
    id: "001"
    name: orang-db
    env: prod
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:j6M5jv6e,iv:GkBz+WqNB25GPNiwO9MURr4RzwfjmOouBFqX3mWWqM8=,tag:CI6bK4RpZ+VHssQYvFTc6A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gmuUq827ag4=,iv:MvxiUk0VlT+pjFJuyllPBJeNxeGa8rCabtdqHhpNg4Q=,tag:OYs6ODjdDPMJEVEeaXsCdQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:eqmSSPgGoo4=,iv:mh+CNtehEkYSgJGlwrp5PAunkWSzow4RYZgietoscWE=,tag:ZnEW/TcNFYJN+76agUHAtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZVJ1bGhWREhHME90TTNX
            TmM5VVpCaDVjSGNWTWNFQmpHVXYwanJ6OTJJCjB1S0IxdExmeXlOUVpGN2JjV1JR
            d2tWaDF6OVhtcTc2MFBaTWkwY3dURFEKLS0tIERQRVdTVGZGSU1VeEhUbEEyTHV4
            TXcxYUluVGZpSzVDM0JjRklMcFVrOGsKOr9XhiWG1HGJIllf5LakPnSHEOjjWcFH
            AlJz8ydVOoKzCgrQowqouZuKo+wtUEJgnDce/ha6hEDxX34yIwB5Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T03:23:00Z"
    mac: ENC[AES256_GCM,data:2ysFXSK0KwQcIiGsaeJhSteMV2BfjeuGB/w3Z7pMQgIgr0RR32P6I1ZEe3yFSi3ST1pn8DsncgsW0rFpTVnY0GANslGKQKyDRw0mIzQ7PkU2Atg8xMbUl52pgKistf8edQJ9jHwRP342lrWNw7il/QaDDKMLw8i1sNwI3apSDog=,iv:nlx0VnslqlwP9h7cn0DTK9Mwa5yaVPFaY1bWkyGfd5M=,tag:h2HiZHvgf+fMa6SvXxXJ9Q==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
