apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "base-chart.name" . }}
  namespace: {{ if eq .Values.app.env "testing" }}testing{{ else }}{{ .Values.app.id }}-{{ .Values.app.name | replace "-db" "" }}{{ end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/id: {{ .Values.app.id | quote }}
    app.kubernetes.io/name: {{ .Values.app.name | quote }}
