namespace: testing
controllerType: StatefulSet
isDatabase: true
app: { id: "003", name: "diwa-app-db", env: "testing" }
image: { repository: "postgres", tag: "15-alpine" }
service: { port: 5432, targetPort: 5432 }
secretData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin123"
  POSTGRES_DB: "diwa_db"
storage: { size: "2Gi" }
