namespace: testing
controllerType: StatefulSet

app:
  id: "002"
  name: "diwa-app-db"
  env: "testing"

image:
  repository: "postgres"
  tag: "15-alpine"

service:
  port: 5432
  targetPort: 5432

backup:
  enabled: true
  type: "postgres"