namespace: prod
controllerType: StatefulSet
app:
    id: "002"
    name: appkedua-db
    env: prod
image:
    repository: postgres
    tag: 15-alpine
service:
    port: 5432
    targetPort: 5432
secretData:
    POSTGRES_DB: ENC[AES256_GCM,data:u+xi02jFbImM7w1kOKk=,iv:xUTt4uM4FvWNRS3daPqYEmUi7w7tWCMlT9umtRIynfs=,tag:ZtOKfBdZYYSqZqZh5RxrCg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:kTjD3Q==,iv:tWmQZQwV5ZWltD/72d5j6v1o+v4MtA3MVemYYCVStOU=,tag:BR1tOA1IY1zEb0zlKr6txQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:l1uTZMtijcoJoTU=,iv:SDy/x5xj56PyZQ9AmhcC5W6M8UBDuchjBRHv+GYjuyE=,tag:VXRw1PFxerkoNRNhBzYemA==,type:str]
backup:
    enabled: true
    type: postgres
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY3ArcEJOM0krekpFeHBw
            dGFwaG1FQXEzcG9iMTZqWTY4M2hlM0o5dmhBCkRsR2szUFhOdjdtczkzNC9wNXk2
            T05rZ0NIYW1XRWRCQW54UnpaYjdqZTQKLS0tIHZ5T3BPbXNhUlFxUlhpWUNhditF
            c2tzL2hUSWxkd1pTaHREdHg1TlVmQ0UK0pmAgabc9L7+IUCkSXWJS3LQMHf/evqb
            81j3m8Uy5FXpYJ8PJlzJv8kbcbeLN3UEF305Eo/iPJanjBuBZNtXpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T06:10:55Z"
    mac: ENC[AES256_GCM,data:jmSeE/D230wWcq4hrAM8x9FSMtsxcahPlsWywQVz8duotYBSAL2r5mwpsAhPA5UG1Yj7e1S4yPt8rZ5nO3iqyHKYkPkTTeKEYfxXP68uK2gYmOiQexhoT/0SKOw9ptP7VWBiJF+icb5RG+IB+0Cq+dOBdewDGD//txDXI9qixR4=,iv:+7OEp/LNB+vvunSPIukY+HQidHHKUfthLDvoRH3bl28=,tag:T3lBfW3xktPOSzFD9m5aUQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
