namespace: prod
controllerType: Deployment
app:
  id: "001"
  name: "damn-app"
  env: "prod"
image:
  repository: "docker.io/diwamln/damn"
  tag: "latest"
service:
  port: 80
  targetPort: 3000
secretData:
  SECRET_KEY: "orangsehat"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "orangsehat"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin123"
  DOMAIN: "localhost"
  FRONTEND_HOST: "http://localhost:5173"
  ENVIRONMENT: "production"
  PROJECT_NAME: "Full Stack FastAPI Project"
  STACK_NAME: "full-stack-fastapi-project"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173"
  EMAILS_FROM_EMAIL: "info@example.com"
  SMTP_TLS: "True"
  SMTP_SSL: "False"
  SMTP_PORT: "587"
  POSTGRES_SERVER: "postgresql-test.database-test.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fastapi"
  DB_HOST: "svc-damn-app-db-001"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "admin123"
  DB_NAME: "app_db"
  PORT: "3000"