apiVersion: apps/v1
kind: Deployment
metadata:
  name: v002-example-backend # Prefix huruf agar patuh standar DNS-1035
  namespace: 999-testing-apps
  labels:
    app: v002-example-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v002-example-backend
  template:
    metadata:
      labels:
        app: v002-example-backend
    spec:
      imagePullSecrets:
      - name: docker-hub-secret # Kunci akses repo private
      containers:
      - name: api
        image: devopsnaratel/example-backend:build-17-270b1bb-test # Image terbaru dari Jenkins #17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: v002-example-backend-config # Secret environment variables
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: v002-example-backend-service # Wajib diawali huruf
  namespace: 999-testing-apps
spec:
  selector:
    app: v002-example-backend
  ports:
  - port: 80
    targetPort: 3000
