apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v002-example-backend-ingress
  namespace: 999-testing-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: k8s-03.naratel.net.id
    http:
      paths:
      - path: /api/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: v002-example-backend-service
            port:
              number: 80
