apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 002-example-backend-ingress
  namespace: 999-testing-apps
  annotations:
    # Mengarahkan trafik dari /api ke / di sisi aplikasi (Strip Prefix)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Opsional: Jika menggunakan SSL/TLS cert-manager
    # kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx # Pastikan Ingress Controller Nginx sudah terinstal
  rules:
  - host: k8s-03.naratel.net.id
    http:
      paths:
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: 002-example-backend-service # Menghubungkan ke Service backend
            port:
              number: 80 # Port Service ClusterIP Anda
