namespace: prod
controllerType: Deployment
app:
    id: "001"
    name: orang
    env: prod
image:
    repository: docker.io/diwamln/orang
    tag: latest
service:
    port: 80
    targetPort: 3000
secretData:
    SECRET_KEY: ENC[AES256_GCM,data:60Sj+GqM9wTYqg==,iv:rjDMrS+3YzqoDRi72bZ8ZcX9xtGgqGPYYtdh4dminh8=,tag:jFORTgIJiB6WLGoWB9hfGg==,type:str]
    FIRST_SUPERUSER: ENC[AES256_GCM,data:aeoXMl9hmHl1TIlP7Ns/22w=,iv:OtF63o/olQdvbl7N9WdstnL3AmNCDhBojNm41U81Dk8=,tag:XFEV/lSMepD1GQwxCnpskA==,type:str]
    FIRST_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:0/LVA2mt26KdDQ==,iv:Dayql/jvtq6X1azUYMxrxRfnKwHc6dSjPpEmpugBcwU=,tag:US8Q8KXrHz/4iuZxim3MOQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vQ7LYsCNZFo=,iv:qIl1gz24YwyMKQd9OL56oPARY97lIbCyTN4ORtGeaNg=,tag:QyfW9MinuyeXU0P/cw78ag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rzhhdxQvLIQ=,iv:s8EpJN3rtXO8DXNI3mys4U30vNt13If8ouyuOWkS5gI=,tag:zJU8h2iQK47m3rxur45Gcw==,type:str]
    DOMAIN: ENC[AES256_GCM,data:7OJxJbv6997Z,iv:b467JJhUfZDMQhiaNmunKDRUYAosfZi/CC6GA+tTamA=,tag:HmEFSMho1qsRUU0l2AJAnQ==,type:str]
    FRONTEND_HOST: ENC[AES256_GCM,data:DJYDGk1eclNmAe9U81BJDtMcTYpV,iv:ahsOxPM/jmb1XuYd1eUNLdG98oBxp+QIPYeT2kXijW8=,tag:A4pHbBjG76bY7+KC8+N/tw==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:idDGEE3FC1i6+w==,iv:k+jornzV4+IpZEMNfKXAFIyh4G7ua+lns15vQjZTmW4=,tag:pRUpPL2gYZk7xeyx9OqLlg==,type:str]
    PROJECT_NAME: ENC[AES256_GCM,data:Q+rxZ9owJpwB4RlZY1p6gvkIV7WQJObijnQ=,iv:+OMzaoE5pFsPG67FdM7F6uX9NzNO3KsWNiet4fHBC58=,tag:h3hQ3oi8wLgmzNRnYtM4TQ==,type:str]
    STACK_NAME: ENC[AES256_GCM,data:62osTHyM7jrYivHfeD9oVLbW9owmDKf1B6w=,iv:VhZUlAi/H3F4DiRgrHlnL2HFUD/UKeciTz8cZb/blkU=,tag:nIXofZS6VtJBwmyVBt1sRA==,type:str]
    BACKEND_CORS_ORIGINS: ENC[AES256_GCM,data:Jybkz4x7Y8BfBXavfJWrS7ASyqwO/uwVj474saGjig0NMG1Ofkg=,iv:kl0vD+t7LIscKOpId2walgukXuIRBDLATv/NiUPt2AY=,tag:160Ad71LNDtgUup03po4XQ==,type:str]
    EMAILS_FROM_EMAIL: ENC[AES256_GCM,data:Dw7apeNXXVrtqes8K8QFlQ==,iv:+IhYIJ1hBltEyrb+UfgLT8QrpKn56qtX2vdgXsHjACQ=,tag:19a0bpaU0TMt8JEbrZzaVA==,type:str]
    SMTP_TLS: ENC[AES256_GCM,data:gUjV5A==,iv:FahZPSLHBIYds+DWcxh1GIA0ehaN9aEALb4EP7uAHh8=,tag:7ejFhM6UrmlOTatZ1RKZVA==,type:str]
    SMTP_SSL: ENC[AES256_GCM,data:d0PrwtY=,iv:DbLnReS2hMOcsexFRBjiTz1zoM/TMq6houQlOTji+Tk=,tag:OeyxRuj/EA4ybFh9CpYeYQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:TdaZ,iv:xb/4644I9GSYqR4LcSmk4NJEdfRGcwyIvgc4dqCfdIg=,tag:aL2vhzmXGlPlEFiUS4CZfw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:QiF+JvDKiCyjdAJ2kLoLTq7XleHDNyQXma0uk76Q7GOyN9MJGKvIO/fW2i/N08Q=,iv:nj4LVi0tRp8JHfPyf9oC+WN9Im4n1spCL3YcnaV9mWw=,tag:TLAcDO5To017kfNzB3nP8w==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:i+Ab3A==,iv:NEQrvYtpj1uhnS1xQZnAcIjs304d5R+ofY6lYt+pUKk=,tag:0YsWA92UzfKgV+KqTgJsBA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:bq23DgNhUQ==,iv:XirgIfLpgV94lRoyhrk1qajE/kbK/1M9RoHJGFH49oM=,tag:hP4mWRF263A1N6bg8UJoCA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:2HFzDKS3TSGIofWgU/2JFw==,iv:XH8FHGuECc96MTbp0nZm6cd5kPGoZjpVt22n4ft8fSY=,tag:D1rLu4cnif4sa69Q0p0pCA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:r3mBzQ==,iv:shRhT1Dd/zl/Y8V14dKjAS/QbCGslxRUmEXNZoto9YI=,tag:l2xsgKlV2iw69Xz9wnFhVw==,type:str]
    DB_USER: ENC[AES256_GCM,data:qZOS6Ia8shE=,iv:oXVYdCZOEG9bZGD1mNQme3xjfbKpOoaGAieKvIaQWXQ=,tag:bC3WJNN/RqbOk/9U8foWwA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CoQIKw7VCE4=,iv:OZvuM8If9ryUnb+VPA1qznlbmhMWIOqJMe6Y475Ln18=,tag:q6+d8FPedaLAaYrQsWYtDg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:LLWZAa4r,iv:1wSL4Fhpti+4b7+BDqIuUmqxnbT2AyYFCHgopHPpOFI=,tag:qUMUFtrkvDOmgi4d1zhbMQ==,type:str]
    PORT: ENC[AES256_GCM,data:a0kJfQ==,iv:jTeZLPhB+25O2Pv0B2PItK3V152ZhzN9wPRm0V3lapw=,tag:cY7+1Q7wrxH3DcL7XzeHIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZTNDY0FhRWZVdVZEKzlz
            YUliVGd0Rk5ETWdmejViL1NQK3dyaDFhWVZNCmFNbzhMbDBtQVRtWnVSZlAxcDdX
            citrQ01rZi9STHd6N3R5R0hVWU41T2MKLS0tIGZZWFhKRHU0dFJicnJQeWZJaWZo
            ZXI0VmZNZ2JlaEJjelJveWgrUUJYMDQKx0+i64V1ZO/sHiWuP27Npv3zZN/RMBHQ
            eWGqY/2xJBRaGmkkHMlVDywIeHoQzzxNqDVieb+osIe4XAHF3yudNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T03:23:00Z"
    mac: ENC[AES256_GCM,data:KgUcDINGLPRNzCvmuptutWYPnwLDfz6hWXCiXxlQ1IKkYx4Aafy56Aba1Sol+zZaBjcBdSfvFbfB1q7b1NZ/dQf2k+SlvJOt4VNIa4t5/VmzWQRjp5Ov5jA5s3hGN7WiU6JVnuDtgV6SLRr2RonfgyhqSLsg4joxuLUyYQN9FjU=,iv:FPbmbz6QqmWZj3Bl9EHFEcNb6lonLrrTurtj7PoKA4Y=,tag:oxNDjrjPTO6OLiezv0YIjg==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
