namespace: prod
controllerType: Deployment
app:
  id: '001'
  name: ngetesttt
  env: prod
image:
  repository: devopsnaratel/todo-app-php
  tag: build-3-bea2047-dev
service:
  port: 80
  targetPort: 80
backup:
  enabled: true
  type: postgres
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: k8s-03.naratel.net.id
      path: /
