namespace: testing
controllerType: Deployment
app:
    id: "001"
    name: orang
    env: testing
image:
    repository: docker.io/diwamln/orang
    tag: latest
service:
    port: 80
    targetPort: 3000
secretData:
    SECRET_KEY: ENC[AES256_GCM,data:1268gPuSENNsww==,iv:iDIfP4BJd4bitbisRPDJHoxVQKDRIIRL5V6dRptYPPY=,tag:sRKjx11E4AfMzHkqAZ3iTQ==,type:str]
    FIRST_SUPERUSER: ENC[AES256_GCM,data:f/71m2oMZ2yuS6RESEDwqpE=,iv:FVDVl7FquWCtcQ8R7pBv0KBWe6JdbXlvQDgXva64Fks=,tag:IMW+cB2596FT//tCv7j7iA==,type:str]
    FIRST_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:jIcQQU6+o8eXtw==,iv:A21g33OMdhRC71xcKtfVD59Pa0GpQMKMkjHoR/5FRk8=,tag:ulsS/n8ElmQQYMIPKWSmMA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vUgto5NPuyE=,iv:GwMjSIjYSgCfT/Zvz/3IgrTGVQDbfV7XFCUTlAr3dvg=,tag:Ea7UnhmMeNh5DJdms2zyDQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gpjUCglgkSU=,iv:b3/XudUmqhJuKG6Gt4MYfp5/ZQy1S/xVqHXehTSKae0=,tag:QEU3ZRkBI8DEpWrxLUGFbg==,type:str]
    DOMAIN: ENC[AES256_GCM,data:x2UxDC5XRVtS,iv:jDHb9nhuMyDoTJK4ujKvhiHD9wm3r3szX77wl+5jaR8=,tag:YMqfyGTGCl2S+foVDmAPxQ==,type:str]
    FRONTEND_HOST: ENC[AES256_GCM,data:W8gxJzb3tGE9/H1MGfbZYTb5Hd6o,iv:XX1W/s4IGuZ/vC/gfzn1mMwUGB07mzS/t3GgBJHOjEk=,tag:AuB3OzXFr0yCAJ/EJQUJMg==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:HTstNpTFj5ysRA==,iv:WMYyQx7OQyAJKBnsiEqZgU/lChWSXTsR9CgNzMx37Iw=,tag:B54KIUnB1QExPg9e2Ut7iA==,type:str]
    PROJECT_NAME: ENC[AES256_GCM,data:AL2d3dkjwlawxiVC3QjsLHwcCmfIz7jl9wM=,iv:i5iKADmKYaljTjzaQ05ymf4azF9BRLKbuc0J43nT8e4=,tag:Sv/LjAhouj26xg2wgurXyw==,type:str]
    STACK_NAME: ENC[AES256_GCM,data:4Vaho4zL8FhPJpc5qec5YfcfSdCqhWiHOIE=,iv:QnIAq5s9blMHljsHoWJNf1lc67K6dmDdQ4KmXo7fjRM=,tag:EyfSDK86iOJJ5JMIQTSEvA==,type:str]
    BACKEND_CORS_ORIGINS: ENC[AES256_GCM,data:UQcusSG/Hg/vPlfDwjBAXpL9lgFrRnq6AifS7pG7Ae628tXizyI=,iv:GrayWNI+1QtTSpOxQtU2Z3fAUcyqQsBmDwN4jvggwtk=,tag:3lRBrd7/KIL1xIBvDzBrkw==,type:str]
    EMAILS_FROM_EMAIL: ENC[AES256_GCM,data:hpsohzt9sAWI90l2hZVViA==,iv:5boLCdsvZLoMDbCUMxJHt+erlkphzlEFFXoeIUiHgqY=,tag:brYzRnrVMi4dKLNEzOWelg==,type:str]
    SMTP_TLS: ENC[AES256_GCM,data:DEoYgQ==,iv:5dNUPCaAAOSLaPV6W9rjj3WiDif8JHVJcd5heCMHQOs=,tag:FtliuRD6smkW4wrJqjqUmw==,type:str]
    SMTP_SSL: ENC[AES256_GCM,data:PkML+1U=,iv:2zGddi9lUI//KJ7Q2ap+JVtxAv4ERsMwc+qVYLg5K5M=,tag:PvF0fssb20/ASErnoZISvA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Snpj,iv:jq+COu8GspPfV/epkx52zI63VTqdiyw1puCSGfLJFLA=,tag:mNugcvOFZThHFbGHyY1kwg==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:2Zef3EGDV/akXTTXIWoqYyRCDDJNMtX1NlilcpQbhGcvXSELO8DA/MjZeR16FTo=,iv:y6Km+FmpO2z9i5ty6Mowv5zSBvo1EM7nOKgk+dI/UWM=,tag:4LpteW1feyZGrfUP5VQo0A==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:2D0gxw==,iv:4IybZVTTgfABPYwRvsz2pj+O57LqFgOTDr7Gt2hTJbM=,tag:Gsm0EbWv8U7La9Kgjf9dCw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qMtOb+QhTQ==,iv:IWHIQVGwLoRau7c+rNoE7riPsHANVWLQxlopu7zsuQ0=,tag:IavUSeh/X63vyaXUE7H8sg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:WG3fMBuN34Iaeij3U5msiA==,iv:Q/yoKYFi0EE0VfI8CwrFw+1+oeBldzNL1KG63XD8yTE=,tag:36mojdia+CTXdbhgtO9n+Q==,type:str]
    DB_PORT: ENC[AES256_GCM,data:93wMkQ==,iv:gi5U4nooO6NMwvNRhKH/bvBS7QUKYxe2IfKiO26LSbA=,tag:addIEmF7V+SW11bSuhNkjQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:FlOkoyN2Two=,iv:NETCA9TTSNSOa3s4B+vwQ0w4IHkkRPMnIc4bojJwSNs=,tag:vcCIJa+HL9t/rVt6qhhFOA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Jz8JYglHPZQ=,iv:Chcucz0D34NUcDfwuBvz2Sk7xp7GH7C2qVapaALojF0=,tag:j2aSMPDlm+DETWZEFAlZfQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:QXPNxWtM,iv:V9vgWhw0Ssged/yMHSiRQkghJ/bRqEyyx1IqdhC7LzI=,tag:FnaYcXocRSi0LmbYFnLyGw==,type:str]
    PORT: ENC[AES256_GCM,data:SspfwQ==,iv:XKV0KeRVbPRlPiFEWXVX6EIL6bLKEOEe4SmFwH/nhQQ=,tag:TB+XcNqCwvh/6tT92HRo8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZVlJeVN4QnpPMlVwNnB4
            TGo2em03VC8yUnVuYVE2cEE3d0hZbFZ2OGtJCk1MWkVKY0xXUmw1UDM4eUYxV2pR
            SlBPTHdKMnNySDVpdjZDYWgzbUtIa2sKLS0tIHF2RDgvNFRKZDRBd1NsOTd0WXg1
            aFpRYXQybDAwM0p6bzU0K3RKRm5UdzAKmt/HEdZhZ4oCptZt5R7lrJK1kGBOw1ip
            EgZVNd52XNs1I22zZq2FyY/jqUqvhswTa1xFfnv0Nw6lw4oi/UW7Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T03:23:00Z"
    mac: ENC[AES256_GCM,data:q0iPBOhN9A72RG7x4iNvjZm7hU6+iIo5k/1ElORI/e4YjMZHYywfULSxh1zjgaIVlLvOOiLYM7tNEEKGIvsj41er83PzVRSe/Pj9rsT4Og6Bj93UbMQfsMVBUSQMbqHFyt6+tJt0uRFVUgS+LnHfjLR8qnxmjMUd9kE/xK/Iam0=,iv:Mo2DCKCql1ReeNjenxABHy0ombIoDaXjElYQcoACGEI=,tag:PQf00XFmVlNcBaW+fDPGPQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
