namespace: testing
controllerType: Deployment
app:
    id: "001"
    name: todoapp
    env: testing
image:
    repository: devopsnaratel/todo-app-php
    tag: build-3-bea2047-dev
service:
    port: 80
    targetPort: 80
secretData: {}
ingress:
    enabled: true
    className: nginx
    hosts:
        - host: test-k3s-03.naratel.net.id
          path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGVBOWcvb3dUZTIvaW1t
            bzU1NnpxbXRpcnhOOGdqczB1NjhabGpoQTI0ClIwSVkyVXZVUUh4OG5ZNHNnRkxL
            R1N4Rk9XMW01eTROdUxWR1ZTTEYyVnMKLS0tIHFLaUUvSU5jNUNOS3JaRzFrODBR
            a3dUbUxqTjNkOHZtbDl0M0ZCWkFYbEUK75MvbysEMGhSH/SD4o8ABGltSrr9w/XB
            JO2nWSs0V2QVTFoPeJhYN98XZpbgSpjcA4ohUldEzmdZ5ygN+HxsLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:48:36Z"
    mac: ENC[AES256_GCM,data:A6WQn2TLoiIMKwZeGUTA0ajOSrocs/MBhvX3fZO+sdF/dsuaKr7JQuU9TyRKfEAdbaaRQ/i5H+dJRHuqD7EXEr5eWgVv0wEzKLFA6JD26O4I0yD61IGk3O/WWEG/fnKTrX79/NLpHNmLe+QyWtQG5TtTIq3ELUI5C679UNliheY=,iv:insBCiVvPBwS07mX4sY2thpVFpMKK59MBZSYL7fR62s=,tag:i7ZTs+8dlbNmc+Rq9Yq5SQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
