namespace: testing
controllerType: Deployment
app:
    id: "001"
    name: todoapp
    env: testing
image:
    repository: dockerio/devopsnaratel/todo-app-php
    tag: build-3-bea2047-dev
service:
    port: 80
    targetPort: 3000
secretData:
    DB_HOST: ENC[AES256_GCM,data:u1GcGUGwjlQEPLyvlzAsmiRv,iv:Lg8AalbmVcaFm00mmrfKE7iHeKRmKddntjmi3TgJcmg=,tag:/q7pFTsxl2HywzaKkZripA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:yaNUaH1VJnmu/GVQb1Q=,iv:AnCa6r08R068GWFL/67qstn4GGoZ1dCzgmEjmCcYO3Y=,tag:wLkMjLwoMtQ5H3d9MQ5+AQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:p51fDVcmc+P6OOY=,iv:19gzeUmMjaNbouLl9BkvDV22EO53GH75wb0pe3oWI/Y=,tag:TIW/n5DhhiWWZN0U4QEziA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:dRECIg==,iv:6AFokoCMpaaecOJxTa/kKRnjYw2ymfGEej1VvXpw12U=,tag:yh7yY6HKahcyDSd8CDLBMw==,type:str]
    DB_USER: ENC[AES256_GCM,data:bLd0if+NNGOrCduO0rygRw==,iv:WQdly4P84YD2Hc+76JCrl1bBeg0vh+sXv0mjAVczHIs=,tag:qomQMWFU2dLtW+yrXmc19w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jnduBIhJ5/v/BTZ3vyBgoz8=,iv:VTetYt5Jpb4tmwmlOjQeFrMacCa/G+I8+hU2cnUgNVM=,tag:eDI6f+sV4DET1aFKcJwR4g==,type:str]
ingress:
    enabled: true
    className: nginx
    hosts:
        - host: test-k8s-03.naratel.net.id
          path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNXpheTcxN2c5TU5oMVRG
            aUJjMmFUTGljZVdxOGhDZ2xKcHBwbit0SEZRCmhrZXJGOWlNWTgwQllHUENsZ0Rz
            NU53NGx6R2RwOVN6NjdwMDNBZlNCUjgKLS0tIHNlY21rSEtUZEUvbFdUYlh2Ym8r
            dDZLZUkvNXN6Z2l6cGZhbnlFRXpRMGsKwCRrWKr4E2U2+PUqxK5h8/YNOttdgRrE
            Szs2lH5TheijN4DaX63/3WFi5tkdQupeI0TApINx32itEHP1slazvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T03:30:59Z"
    mac: ENC[AES256_GCM,data:Zi1bKt1N1fTCaOz4K2UwKbS86k4BDcRZrv5/sYA0S/o6qt6r4XhtGvrFcekWLpli3d1ABNSLK9T/1qANmI/Gy0aEv80qv/wmhmw8Cow6ZuKfgT7Hdfhxt8irUn2jEzhI0R4qdoTP38IdHEZb6JgRBgaSA98n8wMgTn4IpRgdFAk=,iv:2e2U+PcVZitOQEwN6kPQFTr8Rn6Y9z3NbvQtT8MmQWM=,tag:/uhQy7yhw3rzC7q3XNQSng==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
