namespace: diwa-app-003
controllerType: StatefulSet
isDatabase: true
app: { id: "003", name: "diwa-app-db", env: "prod" }
image: { repository: "postgres", tag: "15-alpine" }
service: { port: 5432, targetPort: 5432 }
secretData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SuperSecurePasswordProd003!"
  POSTGRES_DB: "diwa_prod_db"
storage: { size: "10Gi" }
