namespace: prod
controllerType: Deployment
app:
    id: "001"
    name: todoapp
    env: prod
image:
    repository: devopsnaratel/todo-app-php
    tag: build-3-bea2047-dev
service:
    port: 80
    targetPort: 80
secretData:
    DB_HOST: ENC[AES256_GCM,data:M56nZBm3OHrLH3aFR2+l6ok93Ue44yUm,iv:lqF6FUFQisXLElEzc2FWez4qS6kqsGPgQylAlgHaehk=,tag:IhPu0JBg9dxcT/+a3DsQVw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Pp/3MEcB8vb7NgY/ljA=,iv:Pmn5ym4ee5kXcX4CYBloK6tmuAtTgyyjWeXMTtPCgGs=,tag:wrORbQlofMjNch0Z75YRmg==,type:str]
    DB_PASS: ENC[AES256_GCM,data:p8hajLW0uWhsYVc=,iv:Kw02gJ4EXlww727Kg/NW5oDRjrZJxdt6KXLt2JWLlSs=,tag:4XlOgx3UxVM0I7FX3bUEUQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:9V7ZgA==,iv:oMkanUCWyCzjm2vhLlFL/4BRS9PaGAiHvTenHXY+eE4=,tag:YmJZ1zpZbU5nA1nxipWUpA==,type:str]
    DB_USER: ENC[AES256_GCM,data:LWuEGMZQugnJoh4YzZD9KQ==,iv:6Xcoa+9Tr7vpo6PLB7OsuBipPwprOw0N/ejWevcXr7I=,tag:dsLfCU4rS1rc3v8VgOYUtQ==,type:str]
backup:
    enabled: true
    type: postgres
ingress:
    enabled: true
    className: nginx
    hosts:
        - host: k3s-03.naratel.net.id
          path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SWFCUVRQc0ZzRzVwNG03
            enQxMlpVNHM4YzhwdUU4UVJnalorcnlTd0RrCmNoR0NMNE5xeTllS2x5aG9LSjdl
            MG1Xc1cxdzFCdUh1c1lUVHVXRUliTTQKLS0tIHpLbUlNb1lRS2c5U051ak1TYWov
            UDUwbEloLy8yWDV6N3U3Qkxrd3Z3ancKSwlIffK3a0UvVifv4RN6sLs32ioBfh/L
            ZLMg0V5SdZB/4IsI+xDaLYGmGuWoh+mA+LzM4+McBf/0/atyx7gHjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:50:57Z"
    mac: ENC[AES256_GCM,data:7d2IE9FuUpwBFWALVe1NmiAEqxSK95KKDaFQ5t1p7RsALC+9cil4/0b8ZcdKPxSsyXjm6Oxvvw4msVpK+2EZewMpNs/jtw4Ae+35Pd7yOGdBZKEARz/gMuA9NlGhzcY3HfuYXyr36OwpPnta5xztoec1wuVPTyRdCt3W8F0Spos=,iv:wOLYLDziSS0Nwy94p9VM6Q+LPIg5jbw3lytM4dkwh0o=,tag:a/a/1GQCs5kpmwnRkxtvOQ==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
