namespace: prod
controllerType: Deployment

app:
  id: "001"
  name: "todoapp"
  env: "prod"

image:
  repository: "devopsnaratel/todo-app-php"
  tag: "build-3-bea2047-dev"

service:
  port: 80
  targetPort: 80

backup:
  enabled: true
  type: "postgres"