namespace: prod
controllerType: Deployment
app:
    id: "001"
    name: todoapp
    env: prod
image:
    repository: devopsnaratel/todo-app-php
    tag: build-3-bea2047-dev
service:
    port: 80
    targetPort: 80
secretData:
    NEW_KEY: ENC[AES256_GCM,data:c7wp,iv:CunVsmYrVGUJxfWIF0sY8CjHLjWKGbTCzkxhhk0ql7I=,tag:gqRRTIXh9OngD3I6TNY6IA==,type:str]
backup:
    enabled: true
    type: postgres
ingress:
    enabled: true
    className: nginx
    hosts:
        - host: k3s-03.naratel.net.id
          path: /
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywhtcmyuhmfa32kfaaxcak4dvq27q9g6m55gqlzu2vlwkgfj24wq3g4ejx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR1VQTDQvN2FGaTNvREJY
            SXI5NXhBSTRmeWxCNFFpNW9aRE1hOEROS3pFCjhpc1plRjlxOFRRcFpSUCszaHF3
            TWxuaXZyVkpPSTR3S0hqcGFYN1B0TjQKLS0tIDA3aXUyYlFSNDE1VHJDMW96RkVK
            a21WSU1jQmxDM0doOGpsa1dHdkdPUmcKC3NgKuKGJUU7Gwq7CsjpfDQihLRmYe2z
            i+JQIsF536/kYJ2SlkKLjpEmL940UozsOQtmpw3xPEG1F3roiYWgfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:48:36Z"
    mac: ENC[AES256_GCM,data:+lZvIKbWUqrgv+1oDhxusAs+fCoo7Q08WM7q28xF6YkS/28vz86zGoz7d2qvA/+SdH4EVSfk5Ok9eAScApF0kl8LBTcQ0FdxFJpmSE+KRU/jpXnZCZBp/MYODBr/w/c8cVco3F/isNvl6if/objh6hLzWu6zN8EJOFDcu67bDnE=,iv:FxWtNnMIrTNvS87HAZZ+GQB4LTv2N7x0AzxDIMqB/7c=,tag:piPI1pYz41sWr+QL+Vx3sw==,type:str]
    pgp: []
    encrypted_regex: ^(secretData)$
    version: 3.9.0
